Fix bad test command in CI workflow

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -13,8 +13,8 @@ jobs:
           submodules: recursive
       - name: patch TAU & link flang
         run: |
-          sed -i 's/#FLANG_NO_MX_OPTS#//' /usr/local/x86_64/lib/Makefile.tau-clang-pthread || true
-          if [[ ! -e /usr/local/bin/flang ]]; then
+          sed -i 's/#FLANG_NO_MX_OPTS#//' /usr/local/x86_64/lib/Makefile.tau-clang-pthread || echo "sed command returned non-zero status"
+          if ! [ -e /usr/local/bin/flang ]; then
             echo "Linking flang-new as flang"
             ln -s /usr/local/bin/flang-new /usr/local/bin/flang
           else
