Try to improve debugging & output of CI
Also, fail CI when initial build attempt fails and initial testing
attempt fails, even if subsequent attempts pass.

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -1,7 +1,5 @@
 name: CI
 on: push
-env: 
-  GIT_SSL_NO_VERIFY: true
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -19,8 +17,33 @@ jobs:
       - name: Configure SALT
         run: cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -Wdev -Wdeprecated -G Ninja -S . -B build
       - name: Compile SALT
+        id: build
         run: |
           echo "Cores: $(nproc) "
-          cmake --build build --parallel $(nproc) || cmake --build build --verbose
+          if cmake --build build --parallel $(nproc) ; then
+            echo "build_status=success" >> $GITHUB_OUTPUT
+          else
+            echo "build_status=failure" >> $GITHUB_OUTPUT
+            echo "::error::Initial build failed, re-attempting build with verbose output but failing CI"
+            echo "Initial build failed, re-attempting build with verbose output but failing CI"
+            if ! cmake --build build --verbose ; then
+              echo "Verbose build failed on second attempt"
+              echo "::error::Verbose build failed on second attempt"
+              exit 1
+            fi
+          fi
       - name: Run Tests
-        run: cd build && ctest -j --output-on-failure || ctest --rerun-failed --verbose
+        working-directory: build
+        run: |
+          if ! ctest -j --output-on-failure ; then
+            echo "::error::Tests failed, re-running tests with verbose output"
+            echo "Tests failed, re-running tests with verbose output"
+            if ! ctest --rerun-failed --verbose ; then
+              echo "Rerunning failed tests failed on second attempt"
+              echo "::error::Rerunning failed tests failed on second attempt"
+            fi
+            exit 1
+          fi
+      - name: Fail CI on build failure
+        if: ${{ steps.build.outputs.build_status == 'failure' }}
+        run: echo "Failing build" ; exit 1
